5.1) Написать задокументированную функцию умножения двух чисел. Для каких типов данная функция будет возвращать практически ценный результат? Написать примеры использования этой функции.

In [ ]:
def umn(a, b):
    """
    Функция умножения двух чисел.

    Параметры:
    a (int, float): Первое число.
    b (int, float): Второе число.

    Возвращает:
    int, float: Результат умножения a на b.
    """
    return a * b
print(umn(5, 3))

5.2) Написать функцию умножения принимающую от одного до трех параметров. Написать примеры использования этой функции с разным количеством параметров.

In [ ]:
def func(*n):
    if len(n) == 1:
        return n[0] ** 2
    elif len(n) == 2:
        return n[0] * n[1]
    elif len(n) == 3:
        return n[0] * n[1] * n[2]
    else:
        return False
print(func(5))
print(func(5, 4))
print(func(5, 4, 3))
print(func(5, 4, 3, 2))

5.3) Функцию из задания 2 вызвать с приведенными ниже аргументами. Для случая a4 выбрать 3 первых и 3 последних значения.
a1 = (15, 10 ,5)
a2 = (3, 1)
a3 = [2, 35, 55]
a4 = (5, 10 ,15, 20)

In [ ]:
def func(*n):
    if len(n) == 1:
        return n[0] ** 2
    elif len(n) == 2:
        return n[0] * n[1]
    elif len(n) == 3:
        return n[0] * n[1] * n[2]
    else:
        return False

a1 = [15, 10, 5]
a2 = [3, 1]
a3 = [2, 35, 55]
a4 = [5, 10, 15, 20]
print(func(*a1))
print(func(*a2))
print(func(*a3))
print(func(*a4[:3]))
print(func(*a4[1:]))

5.4) Реализовать функцию умножения, принимающую неограниченное количество значений. Написать примеры использования этой функции, в том числе с аргументами из задания 3.

In [ ]:
def func(*n):
    if len(n) == 1:
        return n[0] ** 2
    m = 1
    for i in range(len(n)):
        m *= n[i]
    return m

a1 = [15, 10, 5]
a2 = [3, 1]
a3 = [2, 35, 55]
a4 = [5, 10, 15, 20]
print(func(*a1))
print(func(*a2))
print(func(*a3))
print(func(*a4))

5.5) Реализовать функции для выполнения четырех арифмитических операций преобразующих целые числа в целое число. Для двух заранее заданных целых чисел выполнить выбранную пользователем арифметическую операцию.
5.6) Написать калькулятор для строковых выражений вида '<число> <операция> <число>', где <число> - целое число, например 113, <арифмитическая операция> - одна из операций +,-,*,/(деление нацело),%(остаток от деления),^(возведение в степень). Пример calc('13 - 5') -> 8

In [ ]:
def sl(x, y):
    return x + y
def vc(x, y):
    return x - y
def umn(x, y):
    return x * y
def dln(x, y):
    return x // y

s = input()
ch1 = 0
ch2 = 0
oper = ''
i = 0
while s[i].isdigit():
    ch1 *= 10
    ch1 += int(s[i])
    i += 1
while s[i] == ' ':
    i += 1
oper = s[i]
i += 1
while s[i] == ' ':
    i += 1
while i != len(s):
    ch2 *= 10
    ch2 += int(s[i])
    i += 1
if oper == '+':
    print(sl(ch1, ch2))
elif oper == '-':
    print(vc(ch1, ch2))
elif oper == '*':
    print(umn(ch1, ch2))
else:
    print(dln(ch1, ch2))

5.7) Реализовать функцию которая выводит на экран сообщение вида:
'Автомобиль марки: BMW, модели: X5, цвета: белый, 2006 года выпуска, с пробегом: 215 000 км, c номерным знаком: X012АМ77, цена: 1 115 000 руб.'
В функцию передаются именованные параметры изменяемой части сообщения, лубой из параметров может быть не задан пользователем функции и автоматически заменен на разумное сообщение в соответствующей части строки. Получить вывод текстового сообщения для словарей c1, c2.

In [ ]:
def print_car_info(brand='любой', model='любая', color='любой', year=0, mileage=0, license_plate='любой', price=0):
    message = f"Автомобиль марки: {brand}, модели: {model}, цвета: {color}, {year} года выпуска, с пробегом: {mileage} км, с номерным знаком: {license_plate}, цена: {price} руб."
    print(message)
car1 = {
    'brand': 'BMW',
    'model': 'X5',
    'color': 'белый',
    'year': 2006,
    'mileage': 215000,
    'license_plate': 'X012АМ77',
    'price': 1115000
}
car2 = {
    'brand': 'Audi',
    'model': 'A4',
    'color': 'серый',
    'price': 800000
}
print_car_info(**car1)
print_car_info(**car2)
#Автомобиль марки: BMW, модели: X5, цвета: белый, 2006 года выпуска, с пробегом: 215000 км, с номерным знаком: X012АМ77, цена: 1115000 руб.
#Автомобиль марки: любой, модели: A4, цвета: серый, 0 года выпуска, с пробегом: 0 км, с номерным знаком: любой, цена: 800000 руб.

5.8) Написать функцию, которая преобразует целое число (от 0 до 99) в текстовое написание числа на русском языке. Пример: to_text(15) -> 'Пятнадцать'
5.9) Написать функцию, которая преобразует целое число (от 0 до 999) из текстового представления на руссокм языке в число типа int. Пример: to_int('тридцать три') -> 33

In [ ]:
d = {"ноль": 0, "один": 1, "два": 2, "три": 3, "четыре": 4, "пять": 5, "шесть": 6, "семь": 7, "восемь": 8, "девять": 9,
     "десять": 10, "одиннадцать": 11, "двенадцать": 12, "тринадцать": 13, "четырнадцать": 14, "пятнадцать": 15, "шестнадцать": 16, "семнадцать": 17, "восемнадцать": 18, "девятнадцать": 19,
     "двадцать": 20, "тридцать": 30, "сорок": 40, "пятьдесят": 50, "шестьдесят": 60, "семьдесят": 70, "восемьдесят": 80, "девяносто": 90,
     "сто": 100, "двести": 200, "триста": 300, "четыреста": 400, "пятьсот": 500, "шестьсот": 600, "семьсот": 700, "восемьсот": 800, "девятьсот": 900}
def func(n):
    n1 = n // 100 * 100
    n2 = n % 100 // 10 * 10
    n3 = n % 10
    s = ""
    f1 = 1
    f2 = 1
    for k, v in d.items():
        if v == n1:
            if k != "ноль":
                s += k
            else:
                f1 = 0
                break
    if f1:
        s += ' '
    for k, v in d.items():
        if v == n2:
            if k != "ноль":
                s += k
            else:
                f2 = 0
                break
    if f2:
        s += ' '
    for k, v in d.items():
        if v == n3:
            s += k
    return s
print(func(int(input("Enter: "))))

6.1) Написать калькулятор для строковых выражений вида '<число> <операция> <число>', где <число> - не отрицательное целое число меньшее 100, записанное словами, например "тридцать четыре", <арифмитическая операция> - одна из операций "плюс","минус","умножить". Результат выполнения операции вернуть в виде текстового представления числа. Пример calc('двадцать пять плюс тринадцать') -> "тридцать восемь"

In [ ]:
d = {"ноль": 0, "один": 1, "два": 2, "три": 3, "четыре": 4, "пять": 5, "шесть": 6, "семь": 7, "восемь": 8, "девять": 9,
     "десять": 10, "одиннадцать": 11, "двенадцать": 12, "тринадцать": 13, "четырнадцать": 14, "пятнадцать": 15, "шестнадцать": 16, "семнадцать": 17, "восемнадцать": 18, "девятнадцать": 19,
     "двадцать": 20, "тридцать": 30, "сорок":40, "пятьдесят": 50, "шестьдесят": 60, "семьдесят": 70, "восемьдесят": 80, "девяносто": 90}
def int_from_str(s):
    mas = list(map(str, s.split()))
    n = 0
    if len(mas) == 1:
        n = d[mas[0]]
    else:
        n = d[mas[0]]
        n += d[mas[1]]
    return n

def get(d, value):
    for k, v in d.items():
        if v == value:
            return k

def calculate(s):
    mas = list(map(str, s.split()))
    i = 0
    ch1 = ""
    ch2 = ""
    oper = ""
    while 1:
        ch1 += mas[i]
        i += 1
        if mas[i] == "плюс" or mas[i] == "минус" or mas[i] == "умножить":
            oper = mas[i]
            i += 1
            break
        else:
            ch1 += " "
    while 1:
        ch2 += mas[i]
        i += 1
        if i != len(mas):
            ch2 += " "
        else:
            break
    int_ch1 = int(int_from_str(ch1))
    int_ch2 = int(int_from_str(ch2))
    if oper == "плюс":
        if int_ch1 + int_ch2 < 20:
            return (get(d, int_ch1 + int_ch2))
        else:
            if (int_ch1 + int_ch2) % 10 == 0:
                return (get(d, int_ch1 + int_ch2))
            else:
                return (get(d, (int_ch1 + int_ch2) // 10 * 10) + " " + get(d,(int_ch1 + int_ch2) % 10))
    elif oper == "минус":
        if int_ch1 - int_ch2 < 20:
            return (get(d, int_ch1 - int_ch2))
        else:
            if (int_ch1 - int_ch2) % 10 == 0:
                return (get(d, int_ch1 - int_ch2))
            else:
                return (get(d, (int_ch1 - int_ch2) // 10 * 10) + " " + get(d, (int_ch1 - int_ch2) % 10))
    else:
        if int_ch1 * int_ch2 < 20:
            return (get(d, int_ch1 * int_ch2))
        else:
            if (int_ch1 * int_ch2) % 10 == 0:
                return (get(d, int_ch1 * int_ch2))
            else:
                return (get(d, (int_ch1 * int_ch2) // 10 * 10) + " " + get(d, (int_ch1 * int_ch2) % 10))
s = input()
s1 = calculate(s)
print(s1)